version: "3.8"
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "${SPRING_CLOUD_VAULT_TOKEN}"
      VAULT_ADDR: "${SPRING_CLOUD_VAULT_URI}"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-listen-address="0.0.0.0:8200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      retries: 5
      start_period: 5s

  config-service:
    build: .
    container_name: config-service
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      vault:
        condition: service_healthy